### ISSUE TITLE
ConnectionResetError: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by marufaytekin** [udacity/udacidrone#57]
I am getting the following exception when after I send the waypoints to simulator: 
```
Traceback (most recent call last):
  File "/Users/maruf.aytekin/FCND-Motion-Planning-2/motion_planning.py", line 227, in <module>
    drone.start()
  File "/Users/maruf.aytekin/FCND-Motion-Planning-2/motion_planning.py", line 208, in start
    self.connection.start()
  File "/Users/maruf.aytekin/miniconda2/envs/fcnd/lib/python3.6/site-packages/udacidrone/connection/mavlink_connection.py", line 235, in start
    self.dispatch_loop()
  File "/Users/maruf.aytekin/miniconda2/envs/fcnd/lib/python3.6/site-packages/udacidrone/connection/mavlink_connection.py", line 113, in dispatch_loop
    msg = self.wait_for_message()
  File "/Users/maruf.aytekin/miniconda2/envs/fcnd/lib/python3.6/site-packages/udacidrone/connection/mavlink_connection.py", line 199, in wait_for_message
    msg = self._master.recv_match(blocking=True, timeout=1)
  File "/Users/maruf.aytekin/miniconda2/envs/fcnd/lib/python3.6/site-packages/pymavlink/mavutil.py", line 347, in recv_match
    m = self.recv_msg()
  File "/Users/maruf.aytekin/miniconda2/envs/fcnd/lib/python3.6/site-packages/pymavlink/mavutil.py", line 310, in recv_msg
    s = self.recv(n)
  File "/Users/maruf.aytekin/miniconda2/envs/fcnd/lib/python3.6/site-packages/pymavlink/mavutil.py", line 968, in recv
    data = self.port.recv(n)
ConnectionResetError: [Errno 54] Connection reset by peer
```
I am getting this error when I uset the connection timeout to 600 in this file: https://github.com/marufaytekin/FCND-Motion-Planning/blob/master/motion_planning.py `    conn = MavlinkConnection('tcp:{0}:{1}'.format(args.host, args.port), timeout=600)` 

Any idea where shoul dI be looking?

**Comment by pramodatre** [comment]
I'm having the same issue when using FCND simulator on macOS. Any help in resolving this issue will be greatly appreciated as this issue blocks us from trying new ideas with the FCND simulator.

**Comment by MDanish99** [comment]
I am having the same issue when using FCND simulator on macOS.

**Comment by marufaytekin** [comment]
I think I fixed it with a try-catch block: https://github.com/marufaytekin/FCND-Motion-Planning/blob/main/motion_planning.py
